/* automatically generated from ../../src/lightdm-gtk-greeter.glade */
#ifdef __SUNPRO_C
#pragma align 4 (lightdm_gtk_greeter_ui)
#endif
#ifdef __GNUC__
static const char lightdm_gtk_greeter_ui[] __attribute__ ((__aligned__ (4))) =
#else
static const char lightdm_gtk_greeter_ui[] =
#endif
{
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?><interface><requires lib=\"gt"
  "k+\" version=\"3.4\"/><requires lib=\"greeter_menu_bar\" version=\"1.0\""
  "/><object class=\"GtkAccelGroup\" id=\"a11y_accelgroup\"/><object class"
  "=\"GtkEventBox\" id=\"panel_window\"><property name=\"name\">panel_wind"
  "ow</property><property name=\"visible\">True</property><property name=\""
  "can_focus\">False</property><property name=\"valign\">start</property><"
  "child><object class=\"GreeterMenuBar\" id=\"menubar\"><property name=\""
  "name\">menubar</property><property name=\"visible\">True</property><pro"
  "perty name=\"can_focus\">False</property><property name=\"pack_directio"
  "n\">rtl</property><signal name=\"key-press-event\" handler=\"menubar_ke"
  "y_press_cb\" swapped=\"no\"/><child><object class=\"GtkMenuItem\" id=\""
  "power_menuitem\"><property name=\"name\">power_menuitem</property><prop"
  "erty name=\"visible\">True</property><property name=\"can_focus\">False"
  "</property><child type=\"submenu\"><object class=\"GtkMenu\" id=\"power"
  "_menu\"><property name=\"visible\">True</property><property name=\"can_"
  "focus\">False</property><property name=\"accel_group\">power_accelgroup"
  "</property><child><object class=\"GtkMenuItem\" id=\"suspend_menuitem\""
  "><property name=\"visible\">True</property><property name=\"can_focus\""
  ">False</property><property name=\"label\" translatable=\"yes\">Suspend<"
  "/property><signal name=\"activate\" handler=\"suspend_cb\" swapped=\"no"
  "\"/></object></child><child><object class=\"GtkMenuItem\" id=\"hibernat"
  "e_menuitem\"><property name=\"visible\">True</property><property name=\""
  "can_focus\">False</property><property name=\"label\" translatable=\"yes"
  "\">Hibernate</property><signal name=\"activate\" handler=\"hibernate_cb"
  "\" swapped=\"no\"/></object></child><child><object class=\"GtkMenuItem\""
  " id=\"restart_menuitem\"><property name=\"visible\">True</property><pro"
  "perty name=\"can_focus\">False</property><property name=\"label\" trans"
  "latable=\"yes\">Restart...</property><signal name=\"activate\" handler="
  "\"restart_cb\" swapped=\"no\"/></object></child><child><object class=\""
  "GtkMenuItem\" id=\"shutdown_menuitem\"><property name=\"use_action_appe"
  "arance\">False</property><property name=\"visible\">True</property><pro"
  "perty name=\"can_focus\">False</property><property name=\"accel_path\">"
  "&lt;Login&gt;/power/shutdown</property><property name=\"label\" transla"
  "table=\"yes\">Shut Down...</property><signal name=\"activate\" handler="
  "\"shutdown_cb\" swapped=\"no\"/></object></child></object></child></obj"
  "ect></child><child><object class=\"GtkMenuItem\" id=\"a11y_menuitem\"><"
  "property name=\"name\">a11y_menuitem</property><property name=\"visible"
  "\">True</property><property name=\"can_focus\">False</property><child t"
  "ype=\"submenu\"><object class=\"GtkMenu\" id=\"a11y_menu\"><property na"
  "me=\"visible\">True</property><property name=\"can_focus\">False</prope"
  "rty><property name=\"accel_group\">a11y_accelgroup</property><child><ob"
  "ject class=\"GtkCheckMenuItem\" id=\"large_font_menuitem\"><property na"
  "me=\"use_action_appearance\">False</property><property name=\"visible\""
  ">True</property><property name=\"can_focus\">False</property><property "
  "name=\"accel_path\">&lt;Login&gt;/a11y/font</property><property name=\""
  "label\" translatable=\"yes\">Large Font</property><signal name=\"toggle"
  "d\" handler=\"a11y_font_cb\" swapped=\"no\"/></object></child><child><o"
  "bject class=\"GtkCheckMenuItem\" id=\"high_contrast_menuitem\"><propert"
  "y name=\"use_action_appearance\">False</property><property name=\"visib"
  "le\">True</property><property name=\"can_focus\">False</property><prope"
  "rty name=\"accel_path\">&lt;Login&gt;/a11y/contrast</property><property"
  " name=\"label\" translatable=\"yes\">High Contrast</property><signal na"
  "me=\"toggled\" handler=\"a11y_contrast_cb\" swapped=\"no\"/></object></"
  "child><child><object class=\"GtkCheckMenuItem\" id=\"keyboard_menuitem\""
  "><property name=\"use_action_appearance\">False</property><property nam"
  "e=\"visible\">True</property><property name=\"can_focus\">False</proper"
  "ty><property name=\"accel_path\">&lt;Login&gt;/a11y/keyboard</property>"
  "<property name=\"label\" translatable=\"yes\">On Screen Keyboard</prope"
  "rty><property name=\"use_underline\">True</property><signal name=\"togg"
  "led\" handler=\"a11y_keyboard_cb\" swapped=\"no\"/></object></child><ch"
  "ild><object class=\"GtkCheckMenuItem\" id=\"reader_menuitem\"><property"
  " name=\"use_action_appearance\">False</property><property name=\"visibl"
  "e\">True</property><property name=\"can_focus\">False</property><proper"
  "ty name=\"accel_path\">&lt;Login&gt;/a11y/reader</property><property na"
  "me=\"label\" translatable=\"yes\">Screen Reader</property><property nam"
  "e=\"use_underline\">True</property><signal name=\"toggled\" handler=\"a"
  "11y_reader_cb\" swapped=\"no\"/></object></child></object></child></obj"
  "ect></child><child><object class=\"GtkMenuItem\" id=\"language_menuitem"
  "\"><property name=\"name\">language_menuitem</property><property name=\""
  "visible\">True</property><property name=\"can_focus\">False</property><"
  "property name=\"label\">[language_code]</property><child type=\"submenu"
  "\"><object class=\"GtkMenu\" id=\"language_menu\"><property name=\"visi"
  "ble\">True</property><property name=\"can_focus\">False</property></obj"
  "ect></child></object></child><child><object class=\"GtkMenuItem\" id=\""
  "session_menuitem\"><property name=\"name\">session_menuitem</property><"
  "property name=\"visible\">True</property><property name=\"can_focus\">F"
  "alse</property><child type=\"submenu\"><object class=\"GtkMenu\" id=\"s"
  "ession_menu\"><property name=\"visible\">True</property><property name="
  "\"can_focus\">False</property></object></child></object></child><child>"
  "<object class=\"GtkMenuItem\" id=\"layout_menuitem\"><property name=\"n"
  "ame\">layout_menuitem</property><property name=\"visible\">True</proper"
  "ty><property name=\"can_focus\">False</property><property name=\"label\""
  ">[layout]</property><child type=\"submenu\"><object class=\"GtkMenu\" i"
  "d=\"layout_menu\"><property name=\"visible\">True</property><property n"
  "ame=\"can_focus\">False</property></object></child></object></child><ch"
  "ild><object class=\"GtkSeparatorMenuItem\" id=\"clock_menuitem\"><prope"
  "rty name=\"name\">clock_menuitem</property><property name=\"can_focus\""
  ">False</property></object></child><child><object class=\"GtkSeparatorMe"
  "nuItem\" id=\"host_menuitem\"><property name=\"name\">host_menuitem</pr"
  "operty><property name=\"can_focus\">False</property></object></child></"
  "object></child><style><class name=\"background\"/></style></object><obj"
  "ect class=\"GtkAccelGroup\" id=\"power_accelgroup\"/><object class=\"Gt"
  "kEventBox\" id=\"power_window\"><property name=\"name\">power_window</p"
  "roperty><property name=\"can_focus\">False</property><property name=\"h"
  "align\">center</property><property name=\"valign\">center</property><si"
  "gnal name=\"key-press-event\" handler=\"power_window_key_press_event_cb"
  "\" swapped=\"no\"/><child><object class=\"GtkBox\" id=\"box3\"><propert"
  "y name=\"visible\">True</property><property name=\"can_focus\">False</p"
  "roperty><property name=\"orientation\">vertical</property><child><objec"
  "t class=\"GtkEventBox\" id=\"power_content_frame\"><property name=\"nam"
  "e\">content_frame</property><property name=\"visible\">True</property><"
  "property name=\"can_focus\">False</property><child><object class=\"GtkG"
  "rid\" id=\"grid2\"><property name=\"visible\">True</property><property "
  "name=\"can_focus\">False</property><property name=\"margin_left\">24</p"
  "roperty><property name=\"margin_right\">24</property><property name=\"m"
  "argin_top\">24</property><property name=\"margin_bottom\">24</property>"
  "<property name=\"row_spacing\">6</property><property name=\"column_spac"
  "ing\">6</property><child><object class=\"GtkImage\" id=\"power_icon\"><"
  "property name=\"visible\">True</property><property name=\"can_focus\">F"
  "alse</property><property name=\"margin_left\">6</property><property nam"
  "e=\"margin_right\">12</property><property name=\"margin_top\">6</proper"
  "ty><property name=\"margin_bottom\">6</property><property name=\"stock\""
  ">gtk-missing-image</property></object><packing><property name=\"left_at"
  "tach\">0</property><property name=\"top_attach\">0</property><property "
  "name=\"height\">2</property></packing></child><child><object class=\"Gt"
  "kLabel\" id=\"power_title\"><property name=\"visible\">True</property><"
  "property name=\"can_focus\">False</property><property name=\"halign\">s"
  "tart</property><property name=\"margin_bottom\">6</property><property n"
  "ame=\"hexpand\">True</property><property name=\"label\">[title]</proper"
  "ty><attributes><attribute name=\"weight\" value=\"semibold\"/></attribu"
  "tes></object><packing><property name=\"left_attach\">1</property><prope"
  "rty name=\"top_attach\">0</property></packing></child><child><object cl"
  "ass=\"GtkLabel\" id=\"power_text\"><property name=\"visible\">True</pro"
  "perty><property name=\"can_focus\">False</property><property name=\"hal"
  "ign\">start</property><property name=\"hexpand\">True</property><proper"
  "ty name=\"label\">[text]</property></object><packing><property name=\"l"
  "eft_attach\">1</property><property name=\"top_attach\">1</property></pa"
  "cking></child></object></child></object><packing><property name=\"expan"
  "d\">False</property><property name=\"fill\">True</property><property na"
  "me=\"position\">0</property></packing></child><child><object class=\"Gt"
  "kEventBox\" id=\"power_buttonbox_frame\"><property name=\"name\">button"
  "box_frame</property><property name=\"visible\">True</property><property"
  " name=\"can_focus\">False</property><child><object class=\"GtkButtonBox"
  "\" id=\"buttonbox1\"><property name=\"visible\">True</property><propert"
  "y name=\"can_focus\">False</property><property name=\"margin_left\">24<"
  "/property><property name=\"margin_right\">24</property><property name=\""
  "margin_top\">24</property><property name=\"margin_bottom\">24</property"
  "><property name=\"spacing\">6</property><property name=\"layout_style\""
  ">end</property><child><object class=\"GtkButton\" id=\"power_cancel_but"
  "ton\"><property name=\"label\" translatable=\"yes\">Cancel</property><p"
  "roperty name=\"name\">cancel_button</property><property name=\"visible\""
  ">True</property><property name=\"can_focus\">True</property><property n"
  "ame=\"receives_default\">False</property><signal name=\"clicked\" handl"
  "er=\"power_button_clicked_cb\" swapped=\"no\"/></object><packing><prope"
  "rty name=\"expand\">False</property><property name=\"fill\">True</prope"
  "rty><property name=\"position\">0</property></packing></child><child><o"
  "bject class=\"GtkButton\" id=\"power_ok_button\"><property name=\"label"
  "\" translatable=\"yes\">OK</property><property name=\"name\">power_ok_b"
  "utton</property><property name=\"visible\">True</property><property nam"
  "e=\"can_focus\">True</property><property name=\"receives_default\">Fals"
  "e</property><signal name=\"clicked\" handler=\"power_button_clicked_cb\""
  " swapped=\"no\"/></object><packing><property name=\"expand\">False</pro"
  "perty><property name=\"fill\">True</property><property name=\"position\""
  ">1</property></packing></child></object></child></object><packing><prop"
  "erty name=\"expand\">False</property><property name=\"fill\">True</prop"
  "erty><property name=\"position\">1</property></packing></child></object"
  "></child><style><class name=\"background\"/></style></object><object cl"
  "ass=\"GtkOverlay\" id=\"screen_overlay\"><property name=\"name\">screen"
  "</property><property name=\"can_focus\">False</property><property name="
  "\"hexpand\">True</property><property name=\"vexpand\">True</property><s"
  "ignal name=\"get-child-position\" handler=\"screen_overlay_get_child_po"
  "sition_cb\" swapped=\"no\"/><child><object class=\"GtkEventBox\" id=\"s"
  "creen_overlay_child\"><property name=\"visible\">True</property><proper"
  "ty name=\"can_focus\">False</property><child><placeholder/></child></ob"
  "ject><packing><property name=\"index\">-1</property></packing></child><"
  "style><class name=\"lightdm-gtk-greeter\"/></style></object><object cla"
  "ss=\"GtkListStore\" id=\"user_liststore\"><columns><column type=\"gchar"
  "array\"/><column type=\"gchararray\"/><column type=\"gint\"/></columns>"
  "</object><object class=\"GtkEventBox\" id=\"login_window\"><property na"
  "me=\"name\">login_window</property><property name=\"visible\">True</pro"
  "perty><property name=\"can_focus\">False</property><property name=\"hal"
  "ign\">start</property><property name=\"valign\">start</property><child>"
  "<object class=\"GtkBox\" id=\"login_box\"><property name=\"name\">login"
  "_box</property><property name=\"visible\">True</property><property name"
  "=\"can_focus\">False</property><property name=\"orientation\">vertical<"
  "/property><child><object class=\"GtkFrame\" id=\"content_frame\"><prope"
  "rty name=\"name\">content_frame</property><property name=\"visible\">Tr"
  "ue</property><property name=\"can_focus\">False</property><property nam"
  "e=\"label_xalign\">0</property><property name=\"shadow_type\">none</pro"
  "perty><child><object class=\"GtkGrid\" id=\"grid1\"><property name=\"vi"
  "sible\">True</property><property name=\"can_focus\">False</property><pr"
  "operty name=\"margin_left\">24</property><property name=\"margin_right\""
  ">24</property><property name=\"margin_top\">24</property><property name"
  "=\"row_spacing\">6</property><property name=\"column_spacing\">18</prop"
  "erty><child><object class=\"GtkEntry\" id=\"username_entry\"><property "
  "name=\"name\">prompt_entry</property><property name=\"can_focus\">True<"
  "/property><property name=\"hexpand\">True</property><property name=\"in"
  "visible_char\">\342\200\242</property><property name=\"placeholder_text"
  "\" translatable=\"yes\">Enter your username</property><signal name=\"fo"
  "cus-out-event\" handler=\"username_focus_out_cb\" swapped=\"no\"/><sign"
  "al name=\"key-press-event\" handler=\"username_key_press_cb\" swapped=\""
  "no\"/></object><packing><property name=\"left_attach\">1</property><pro"
  "perty name=\"top_attach\">0</property></packing></child><child><object "
  "class=\"GtkEntry\" id=\"password_entry\"><property name=\"name\">prompt"
  "_entry</property><property name=\"width_request\">200</property><proper"
  "ty name=\"visible\">True</property><property name=\"can_focus\">True</p"
  "roperty><property name=\"margin_bottom\">12</property><property name=\""
  "hexpand\">True</property><property name=\"visibility\">False</property>"
  "<property name=\"invisible_char\">\342\200\242</property><property name"
  "=\"primary_icon_activatable\">False</property><property name=\"secondar"
  "y_icon_activatable\">False</property><property name=\"placeholder_text\""
  " translatable=\"yes\">Enter your password</property><signal name=\"acti"
  "vate\" handler=\"login_cb\" swapped=\"no\"/><signal name=\"key-press-ev"
  "ent\" handler=\"password_key_press_cb\" swapped=\"no\"/></object><packi"
  "ng><property name=\"left_attach\">1</property><property name=\"top_atta"
  "ch\">1</property></packing></child><child><object class=\"GtkIconView\""
  " id=\"iconview1\"><property name=\"visible\">True</property><property n"
  "ame=\"can_focus\">True</property><property name=\"margin\">6</property>"
  "<property name=\"vscroll_policy\">natural</property><property name=\"mo"
  "del\">user_liststore</property></object><packing><property name=\"left_"
  "attach\">0</property><property name=\"top_attach\">0</property><propert"
  "y name=\"height\">3</property></packing></child><child><placeholder/></"
  "child></object></child><child type=\"label_item\"><placeholder/></child"
  "></object><packing><property name=\"expand\">True</property><property n"
  "ame=\"fill\">True</property><property name=\"position\">0</property></p"
  "acking></child><child><object class=\"GtkInfoBar\" id=\"greeter_infobar"
  "\"><property name=\"name\">greeter_infobar</property><property name=\"c"
  "an_focus\">False</property><child internal-child=\"action_area\"><objec"
  "t class=\"GtkButtonBox\" id=\"infobar-action_area\"><property name=\"ca"
  "n_focus\">False</property><property name=\"layout_style\">end</property"
  "><child><placeholder/></child></object><packing><property name=\"expand"
  "\">False</property><property name=\"fill\">False</property><property na"
  "me=\"position\">-1</property></packing></child><child internal-child=\""
  "content_area\"><object class=\"GtkBox\" id=\"infobar-content_area\"><pr"
  "operty name=\"can_focus\">False</property><child><object class=\"GtkLab"
  "el\" id=\"message_label\"><property name=\"visible\">True</property><pr"
  "operty name=\"can_focus\">False</property><property name=\"label\" comm"
  "ents=\"This is a placeholder string and will be replaced with a message"
  " from PAM\">[message]</property></object><packing><property name=\"expa"
  "nd\">True</property><property name=\"fill\">True</property><property na"
  "me=\"position\">0</property></packing></child></object><packing><proper"
  "ty name=\"expand\">False</property><property name=\"fill\">True</proper"
  "ty><property name=\"position\">-1</property></packing></child></object>"
  "<packing><property name=\"expand\">False</property><property name=\"fil"
  "l\">True</property><property name=\"position\">1</property></packing></"
  "child><child><object class=\"GtkFrame\" id=\"buttonbox_frame\"><propert"
  "y name=\"name\">buttonbox_frame</property><property name=\"visible\">Tr"
  "ue</property><property name=\"can_focus\">False</property><property nam"
  "e=\"label_xalign\">0</property><property name=\"shadow_type\">none</pro"
  "perty><child><object class=\"GtkBox\" id=\"box2\"><property name=\"visi"
  "ble\">True</property><property name=\"can_focus\">False</property><prop"
  "erty name=\"margin_left\">24</property><property name=\"margin_right\">"
  "24</property><property name=\"margin_bottom\">24</property><child><obje"
  "ct class=\"GtkButton\" id=\"cancel_button\"><property name=\"label\" tr"
  "anslatable=\"yes\">Cancel</property><property name=\"name\">cancel_butt"
  "on</property><property name=\"visible\">True</property><property name=\""
  "can_focus\">True</property><property name=\"receives_default\">False</p"
  "roperty><signal name=\"clicked\" handler=\"cancel_cb\" swapped=\"no\"/>"
  "</object><packing><property name=\"expand\">False</property><property n"
  "ame=\"fill\">True</property><property name=\"position\">0</property></p"
  "acking></child><child><object class=\"GtkButton\" id=\"login_button\"><"
  "property name=\"label\" translatable=\"yes\">Log In</property><property"
  " name=\"name\">login_button</property><property name=\"visible\">True</"
  "property><property name=\"can_focus\">True</property><property name=\"r"
  "eceives_default\">False</property><signal name=\"clicked\" handler=\"lo"
  "gin_cb\" swapped=\"no\"/></object><packing><property name=\"expand\">Fa"
  "lse</property><property name=\"fill\">True</property><property name=\"p"
  "ack_type\">end</property><property name=\"position\">1</property></pack"
  "ing></child></object></child><child type=\"label_item\"><placeholder/><"
  "/child></object><packing><property name=\"expand\">False</property><pro"
  "perty name=\"fill\">True</property><property name=\"position\">2</prope"
  "rty></packing></child></object></child><style><class name=\"background\""
  "/></style></object></interface>"
};

static const unsigned lightdm_gtk_greeter_ui_length = 17704u;

